@echo off
cd D:\Documents\source\repos\PerfectMYGHY\scratch-gui
echo 正在生成Scratch GUI...
.\build-dist.bat
echo 正在配置文件名...
python rename.py
cd D:\Documents\source\repos\PerfectMYGHY\scratch
echo 正在复制...
.\copy-code-from-scratch-gui.bat
echo 开始编译...
set NODE_ENV=production
npm run build:high
